"""directory overrides

Revision ID: 12e7e74ecc00
Revises: 9586f767761b
Create Date: 2026-07-19 23:45:34.484462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12e7e74ecc00'
down_revision: Union[str, Sequence[str], None] = '9586f767761b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directory_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_directory_overrides'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('directory_overrides')
    # ### end Alembic commands ###
