"""lessons/unparsed_cells: cell_key — координата породившей ячейки.

"таблица:строка:колонка" в пределах документа, тот же ключ, что у Ledger.
Нужен prove(): без связи «строка БД → ячейка» доказательства сверяли множества
текстов, и ячейки-близнецы, внутриячеечная потеря пар и мусорные строки
проходили инвариант молча. NULL — ручные пары/сид и фрагменты без ячейки
(аномалии календаря недель, неразобранные куски сессии).

Revision ID: 602ba469f734
Revises: 90b793c49028
Create Date: 2026-07-17 19:19:17.904473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '602ba469f734'
down_revision: Union[str, Sequence[str], None] = '90b793c49028'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('cell_key', sa.String(length=50), nullable=True))
    op.add_column('unparsed_cells', sa.Column('cell_key', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unparsed_cells', 'cell_key')
    op.drop_column('lessons', 'cell_key')
    # ### end Alembic commands ###
