"""schedule importer: document links, diff, slot key

Три правки, каждая куплена прогоном 29 реальных файлов ЮФУ:

* lessons.document_id / exam_events.document_id — иначе переразбор
  изменившегося файла не может заменить его данные: module_id nullable, и пары
  без модуля (основной случай) не привязаны к документу ничем;
* uq_lessons_slot расширен document_id, date_constraint_raw и subject. Старый
  ключ запрещал то, что в источнике законно: осень и весна у одной группы
  (разные файлы), 'До 17.12'/'24.12' в одной ячейке (разные даты) и два
  параллельных занятия (разные предметы). Импорт весны падал на уникальности
  осени;
* import_diffs — «было/стало» при подмене файла: молча перезаписать расписание
  студента нельзя.

ВНИМАНИЕ к downgrade: он возвращает узкий уникальный индекс и на импортированных
данных упадёт на дублях — это не дефект, а то же самое ограничение, из-за
которого индекс и расширяли. Сначала почистить lessons.

Revision ID: 90b793c49028
Revises: a7b2aaf6d559
Create Date: 2026-07-17 14:24:16.849098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90b793c49028'
down_revision: Union[str, Sequence[str], None] = 'a7b2aaf6d559'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_diffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('sha256_before', sa.String(length=64), nullable=False),
    sa.Column('sha256_after', sa.String(length=64), nullable=False),
    sa.Column('added', sa.Integer(), nullable=False),
    sa.Column('removed', sa.Integer(), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['schedule_documents.id'], name=op.f('fk_import_diffs_document_id_schedule_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_diffs'))
    )
    op.create_index(op.f('ix_import_diffs_document_id'), 'import_diffs', ['document_id'], unique=False)
    op.add_column('exam_events', sa.Column('document_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_exam_events_document_id'), 'exam_events', ['document_id'], unique=False)
    op.create_foreign_key(op.f('fk_exam_events_document_id_schedule_documents'), 'exam_events', 'schedule_documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.add_column('lessons', sa.Column('document_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('uq_lessons_slot'), table_name='lessons')
    op.create_index('uq_lessons_slot', 'lessons', ['group_id', 'weekday', 'pair_number', sa.literal_column("coalesce(week_type, '')"), 'subgroup', sa.literal_column('coalesce(module_id, -1)'), sa.literal_column('coalesce(document_id, -1)'), sa.literal_column("coalesce(date_constraint_raw, '')"), 'subject'], unique=True)
    op.create_index(op.f('ix_lessons_document_id'), 'lessons', ['document_id'], unique=False)
    op.create_foreign_key(op.f('fk_lessons_document_id_schedule_documents'), 'lessons', 'schedule_documents', ['document_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_lessons_document_id_schedule_documents'), 'lessons', type_='foreignkey')
    op.drop_index(op.f('ix_lessons_document_id'), table_name='lessons')
    op.drop_index('uq_lessons_slot', table_name='lessons')
    op.create_index(op.f('uq_lessons_slot'), 'lessons', ['group_id', 'weekday', 'pair_number', sa.literal_column("COALESCE(week_type, ''::character varying)"), 'subgroup', sa.literal_column("COALESCE(module_id, '-1'::integer)")], unique=True)
    op.drop_column('lessons', 'document_id')
    op.drop_constraint(op.f('fk_exam_events_document_id_schedule_documents'), 'exam_events', type_='foreignkey')
    op.drop_index(op.f('ix_exam_events_document_id'), table_name='exam_events')
    op.drop_column('exam_events', 'document_id')
    op.drop_index(op.f('ix_import_diffs_document_id'), table_name='import_diffs')
    op.drop_table('import_diffs')
    # ### end Alembic commands ###
