"""contacts source column

Revision ID: 9586f767761b
Revises: 602ba469f734
Create Date: 2026-07-19 18:56:10.336454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9586f767761b'
down_revision: Union[str, Sequence[str], None] = '602ba469f734'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default обязателен: колонка NOT NULL добавляется в таблицу, где
    # уже есть строки, и без значения по умолчанию миграция упала бы на
    # боевой базе. Существующие контакты заведены руками — им 'manual'.
    op.add_column(
        'contacts',
        sa.Column(
            'source',
            sa.String(length=20),
            nullable=False,
            server_default='manual',
        ),
    )
    # Дальше значение проставляет приложение, БД-шный дефолт больше не нужен.
    op.alter_column('contacts', 'source', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'source')
    # ### end Alembic commands ###
