"""subject renames

Revision ID: d96cb86e9d62
Revises: 12e7e74ecc00
Create Date: 2026-07-23 14:41:03.408326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd96cb86e9d62'
down_revision: Union[str, Sequence[str], None] = '12e7e74ecc00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject_renames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_subject', sa.String(length=500), nullable=False),
    sa.Column('display_subject', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subject_renames')),
    sa.UniqueConstraint('match_subject', name=op.f('uq_subject_renames_match_subject'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subject_renames')
    # ### end Alembic commands ###
